spring:
  profiles:
    active: db

  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: ${username_}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true