spring:
  profiles:
    active: env

  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: ${username_}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
